@startuml

package "junit.framework" #DDDDDD {
  interface Test
  class TestSuite
  class TestCase

  Test "*" <|-d- "1" TestSuite
  Test <|.d. TestSuite
  Test <|.d. TestCase
}

class FileReaderTester

TestCase <|-d- FileReaderTester

@enduml